Исправляет ошибку связанную с уничтожением объектов Chain:
Exception ignored in: <bound method Chain.__del__ of <proxy_switcher.chain.Chain object at 0x00000000032A97B8>>
Traceback (most recent call last):
  File "D:\work\proxy-test\proxy_switcher\chain.py", line 628, in __del__
  File "D:\work\proxy-test\proxy_switcher\chain.py", line 632, in finalize
  File "D:\work\proxy-test\proxy_switcher\chain.py", line 649, in _release_pool_proxy
  File "D:\work\proxy-test\proxy_switcher\chain.py", line 547, in release
  File "C:\Python\Python344-64\lib\collections\__init__.py", line 70, in __setitem__
ReferenceError: weakly-referenced object no longer exists